@startuml
title ERD Monitoring Ruangan

' =====================
' LAYOUT & STYLE
' =====================
top to bottom direction
skinparam linetype ortho
skinparam shadowing false

skinparam entity {
  BackgroundColor #c2c8d8
  BorderColor #38bdf8
  FontColor white
  AttributeFontColor white
}

skinparam title {
  FontColor white
}

skinparam backgroundcolor #d3d7e6

' =====================
' ENTITY
' =====================
entity "ADMIN" as ADMIN {
  int id_admin <<PK>>
  --
  string username
  string password
}

entity "RUANGAN" as RUANGAN {
  int id_ruangan <<PK>>
  --
  string nama_ruangan
  string lokasi
  float suhu_min
  float suhu_max
  float kelembapan_min
  float kelembapan_max
}

entity "DEVICE" as DEVICE {
  int id_device <<PK>>
  --
  string kode_device
  string status
  int id_ruangan <<FK>>
}

entity "MONITORING" as MONITORING {
  int id_monitoring <<PK>>
  --
  float suhu
  float kelembapan
  datetime waktu
  int id_device <<FK>>
}

' =====================
' RELATIONSHIP
' =====================
ADMIN ||--o{ RUANGAN : mengelola
RUANGAN ||--o{ DEVICE : memiliki
DEVICE ||--o{ MONITORING : menghasilkan

@enduml
