@startuml Sistem_Parkir_Mall

' Konfigurasi tampilan
skinparam linetype ortho
skinparam shadowing false
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

entity "settings" as settings {
    * id_setting : INT <<PK>>
    --
    * kapasitas_total : INT
    * status_parkir : ENUM('BUKA', 'TUTUP')
}

entity "parking_logs" as logs {
    * id_log : INT <<PK>>
    --
    * waktu : TIMESTAMP
    * arah : ENUM('MASUK', 'KELUAR')
    * kode_pintu : VARCHAR(50)
}

entity "users" as users {
    * id_user : INT <<PK>>
    --
    * username : VARCHAR(50)
    * password : VARCHAR(255)
    * nama_petugas : VARCHAR(100)
}

' Relasi secara logika:
' Admin mengelola setting dan memantau log
users ||--o{ settings : "mengatur"
users ||--o{ logs : "memantau"

note right of logs
  Rumus Sisa Slot:
  Kapasitas - (Count MASUK - Count KELUAR)
end note

@enduml