@startuml
skinparam ActivityBackgroundColor #fdfdfd
skinparam ActivityBorderColor #333333
skinparam ActivityFontSize 12
skinparam DiamondBackgroundColor #e9f5fe
skinparam DiamondBorderColor #004a99

title Flowchart Logika Sistem Parkir Mall Terintegrasi

start
:Kendaraan memutus sinyal **IR Break Beam**;
:Sistem identifikasi **gate_id** dan **gate_type**;

if (Tipe Pintu?) then (Masuk (IN))
    :Cek **current_filled** vs **max_capacity**\npada tabel **parking_levels**;
    
    if (Cek Kapasitas?) then (Masih Tersedia)
        :Kirim Sinyal **BUKA PALANG**;
        
        fork
            :INSERT data baru ke **parking_logs**;
        fork again
            :UPDATE **current_filled** (+1)\ndi tabel **parking_levels**;
        end fork
        
        :Tampilkan pesan "Selamat Datang";
        
        if (Cek Threshold (95%)?) then (Ya)
            :Nyalakan **Lampu Peringatan Merah**\ndi depan gerbang utama;
        else (Tidak)
            :Tetap nyalakan **Lampu Hijau**;
        endif
        
    else (Penuh)
        :Tampilkan pesan "MAAF, PARKIR PENUH"\npada layar LED;
        :Palang Tetap Tertutup;
    endif

else (Keluar (OUT))
    :Validasi Tiket / Pembayaran;
    :Kirim Sinyal **BUKA PALANG**;
    
    fork
        :INSERT data baru ke **parking_logs**;
    fork again
        :UPDATE **current_filled** (-1)\ndi tabel **parking_levels**;
    end fork
    
    :Tampilkan pesan "Terima Kasih";
    
    if (Kapasitas < 95%?) then (Ya)
        :Matikan **Lampu Peringatan Merah**;
    endif
endif

:Kendaraan melewati area sensor;
:Sistem Reset (Sinar Sensor Terhubung Kembali);
stop
@enduml